---
title: "Pagina Web"
author: Alvarado Muñoz, Lesly - Comeca Huaman, Mariela - Delgado Rafael, Jamil - Diaz Saucedo, Yoel - Florida Garcia, Cristian - Luis Marin, Ney.
format: html
editor: visual
output-file: index
theme: darkly
---

# Pasos para crear una página web

1.  Tener mi proyecto
1.  Conectar mi proyecto a GitHub
1.  Tener un archivo en html llamado "index.html"
1.  Hacer push al repositorio
1.  Activar GitHub pages

source('https://inkaverse.com/setup.r')

#Importas datos
```{r}
library(googlesheets4)
library(tidyverse)

url <-"https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=172957346#gid=172957346"
gs<-as_sheets_id(url)

fb<-gs %>%
  range_read("fb")

view(fb)
```


# Modelo lineal
```{r}
modelo <- manova(cbind(leafdw, wue) ~ bloque + geno + riego + riego:geno, data = fb)


anova(modelo)
str(fb)

#Modelo lineal con multibariable
```
```{r}
modelo <- lm(formula = leafdw ~ bloque + geno + riego +riego*geno , data = fb)

anova(modelo)
str(fb)
```

```{r}
modelo <- lm(formula = wue ~ bloque + geno + riego +riego*geno , data = fb)

anova(modelo)
str(fb)
```

# box plot
```{r}

ggplot(fb, aes(x = factor(geno), y = leafdw, fill = factor(riego))) +
  geom_boxplot() +
  labs(title = "Boxplot de Leafdw por Genotipo y Bloque",
       x = "Genotipo",
       y = "Leafdw" ,
       fill = "riego") +
  theme_minimal()

# Crear un boxplot para 'wue' agrupado por los factores 'riego' y 'geno'
ggplot(fb, aes(x = factor(geno), y = wue, fill = factor(riego))) +
  geom_boxplot() +
  labs(title = "Boxplot de WUE por Riego y Genotipo",
       x = "genotipo",
       y = "WUE" ,
       fill = "riego")+
  theme_minimal()


```


# Comparación De Medias
```{r}

```







